### PR TITLE
Added a "Description" field for dataset files

### PR DESCRIPTION
**Pull request by firasalchalabi**

### CODE REVIEW

**Comment by AtilaSaraiva** [comment]
Hey, im a little bit confused, how would we fill the description field?

**Comment by firasalchalabi** [comment]
I thought this was something we'd think about later? I could ask the user to write up a description in the upload script. I'll think about it more and get back to you.

**Comment by AtilaSaraiva** [comment]
Cool, maybe it could be a different file with thr same name as the dataset. The upload script could create this file.

**Comment by firasalchalabi** [comment]
I added a way to fill in the description field. I'll update the upload script accordingly

**Comment by AtilaSaraiva** [comment]
Cool, maybe it could be a different file with thr same name as the dataset. The upload script could create this file.

**Comment by AtilaSaraiva** [comment]
Looking good!

**Pull request merged**
